era dxsys.c
era dxsys.h
era dxsys.crl
era dxterm.c
era dxterm.h
era dxterm.crl
era mancala.c
era mancala.crl

ft -g file://sdk/dxsys.c
ft -g file://sdk/dxsys.h
cc dxsys
era dxsys.c

ft -g file://sdk/dxterm.c
ft -g file://sdk/dxterm.h
cc dxterm
era dxterm.c

ft -g file://mancala/mancala.c
cc mancala
era mancala.c
era dxsys.h
era dxterm.h

clink mancala dxterm dxsys

a:pip a:mancala.com=mancala.com

era dx*.*
era mancala.crl
;submit mancala
mcpdone mancala